### PR TITLE
Update larutils dependency versions to keep up with changes to art and larsoft.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by wesketchum** [comment]
Any reason this PR is going to master and not `develop` ?

**Comment by gartung** [comment]
No. Just using the default branch from `mrb g icaruscode_suite`. You can change the base or I can re-submit.

**Comment by gartung** [comment]
I changed the base.

**Comment by cerati** [comment]
is this part of the cetmodules migration?

**Comment by gartung** [comment]
I created it to have something to use for CI tests. It is not needed now.

**Comment by gartung** [comment]
Although if you build with mrb you will get an error unless the larbatch versions match.

**Pull request closed without merging**
